[package]
authors = ['Parallel Team']
edition = '2018'
name    = 'pallet-loans-rpc'
version = '3.0.0'

[dependencies]
codec                           = { package = 'parity-scale-codec', version = '2.0.0' }
jsonrpc-core                    = '15.0.0'
jsonrpc-core-client             = '15.0.0'
jsonrpc-derive                  = '15.0.0'
serde                           = { version = '1.0.124', features = ['derive'] }
sp-runtime                      = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8' }
sp-api                          = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8' }
sp-blockchain                   = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8' }
sp-core                         = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8' }
primitives                      = { package = 'parallel-primitives', path = '../../../primitives', default-features = false }

pallet-loans-rpc-runtime-api    = { path = 'runtime-api', default-features = false, version = '3.0.0' }
